include: package:carapacik_lints/core.yaml

analyzer:
  exclude:
    - '**/generated/**'
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
formatter:
  page_width: 120
